# **Utils module**

The utils module has a variety of utilities mostly focussed on greping on output files of different codes. This tools combined can be usefull for various porpuses.

**<font color='red'>So far the code supports:</font>**
### **Grepping** tools (either by calling the function or using the **file class**):
- Grepping the **number of electrons** of Quantum Espresso and VASP outputs. *(grep_electrons)*
- Grepping the **Fermi level**. *(grep_fermi)*
- Grep the **lattice parameters**. *(grep_lattice)*
- Grep the **path** from a Quantum Espresso bands.pwi or madyn.in input. *(grep_ticks_QE)*
- Grep the **path** from a KPATH in the [TQC website](https://www.topologicalquantumchemistry.fr/#/) format. (Enter in any compound and click in the Download KPATH link). *(grep_ticks_labels_KPATH)*
- Grep the **phonon grid** from a Quantum Espresso ph.x output. *(grep_ph_grid_points)*
- Grep the **total energy** from a Quantum Espresso ph.x output. *(grep_total_energy)*

### **Transforming** tools (mainly usefull changes of coordinates):
- **K_basis**: Obtaining the reciprocal lattice vectors.
- **cartesian2cryst**: From cartesian to crystal coordinates.
- **cryst2cartesian**: From crystal to cartesian coordinates.
- **cartesian2spherical**: From cartesian to spherical coordinates.
- **spherica2cartesian**: From spherical to cartesian coordinates.
- **cryst2spherical**: From crystal to spherical coordinates.
- **spherical2cryst**: From spherical to crystal coordinates.
- **voigt2cartesian**: From voig notation to cartesian notation.
- **cartesian2voigt**: From cartesian notation to voig notation.
---
>*The **documentation** of every function is accesible with the usual **shift + tab** shortcut.*
---

# **I. Grepping tools**

In [2]:
%load_ext autoreload
%autoreload 2
from yaiv import grep

In [1]:
from yaiv import spectrum

## Electrons

In [6]:
nElectrons=grep.electron_num('data/qe/results_scf/Si.scf.pwo')
print('Quantum espreesso used',nElectrons,'electrons.')
nElectrons=grep.electron_num('data/vasp/RESULTS/OUTCAR_BS')
print('VASP used',nElectrons,'electrons.')

Quantum espreesso used 8 electrons.
VASP used 8 electrons.


## Lattice

In [7]:
print('Basis used by Quantum espresso')
print(grep.lattice('data/qe/results_scf/Si.scf.pwo'))
print()
print('Basis used by VASP')
print(grep.lattice('data/vasp/RESULTS/OUTCAR'))

Basis used by Quantum espresso
[[0.0 2.7343648234158016 2.7343648234158016] [2.7343648234158016 0.0 2.7343648234158016] [2.7343648234158016 2.7343648234158016 0.0]] angstrom

Basis used by VASP
[[0.0 2.734363998 2.734363998] [2.734363998 0.0 2.734363998] [2.734363998 2.734363998 0.0]] angstrom


## Fermi level

In [8]:
#Fermi level
fermi=grep.fermi('data/qe/results_scf/Si.scf.pwo')
print('Quantum espreesso\'s fermi level is',fermi)
fermi=grep.fermi('data/vasp/RESULTS/OUTCAR_SCC')
print('VASP\'s fermi level is',fermi)

Quantum espreesso's fermi level is 6.3627 electron_volt
VASP's fermi level is 6.1723 electron_volt


## Total energy (and energy decomposition)

In [9]:
energy=grep.total_energy('data/qe/results_scf/Si.scf.pwo')
print('Total energy in QE:',energy)
energy=grep.total_energy('data/vasp/RESULTS/OUTCAR')
print('Total energy in VASP:',energy)

Total energy in QE: -93.77214097 rydberg
Total energy in VASP: -0.5820532903697593 rydberg


In [10]:
energy=grep.total_energy('data/qe/results_scf/Si.scf.pwo',decomposition=True)
print('Free energy=',energy.F)
print('Internal energy=',energy.U)
print('Entropy contribution=',energy.TS)
print('Single electron energy=',energy.U_one_electron)
print('Hartree energy=',energy.U_hartree)
print('Exchange-correlation energy=',energy.U_xc)
print('Ewald energy=',energy.U_ewald)

Free energy= -93.77214097 rydberg
Internal energy= -93.76999657 rydberg
Entropy contribution= -0.0021444 rydberg
Single electron energy= 5.73621994 rydberg
Hartree energy= 1.13562264 rydberg
Exchange-correlation energy= -12.81773185 rydberg
Ewald energy= -16.67997833 rydberg


## Stress tensor

In [1]:
print('Stress tensor in QE')
print(grep.stress_tensor('data/qe/results_scf/Si.scf.pwo'))
print()
print('Stress tensor in VASP')
print(grep.stress_tensor('data/vasp/RESULTS/OUTCAR'))

Stress tensor in QE
[[376.7405191442384 0.0 0.0] [0.0 376.7405191442384 0.0] [0.0 0.0 376.7405191442384]] kilobar

Stress tensor in VASP
[[34.82684 -0.0 0.0] [-0.0 34.82684 -0.0] [0.0 -0.0 34.82684]] kilobar


/u/51/gutierm2/unix/Software/YAIV/build/__editable__.yaiv-1.0.0-py3-none-any/yaiv/grep.py:393: UserWarning: According to VASP this is kB units, but when comparing to QE it appears to be GPa.
  warnings.warn(


## K-paths

In [6]:
False is False

True

In [1]:
kpath=grep.kpath('data/qe/results_bands/Si.bands.pwi')
print('QE path:', kpath.labels)
print(kpath.path)
print()
kpath=grep.kpath('data/vasp/RESULTS/KPATH')
print('VASP:', kpath.labels)
print(kpath.path)
print()

QE path: ['X', 'W', 'L', 'Gamma', 'X', 'X_1', 'K', 'U', 'Gamma']
[[0.5 0.0 0.5 20.0] [0.5 0.25 0.75 20.0] [0.5 0.5 0.5 20.0] [0.0 0.0 0.0 20.0] [0.5 0.0 0.5 1.0] [0.5 0.5 1.0 20.0] [0.375 0.375 0.75 20.0] [0.125 0.125 0.25 20.0] [0.0 0.0 0.0 1.0]] _2pi / crystal

VASP: ['X', 'W', 'L', 'Gamma', 'X', 'X_1', 'K', 'U', 'Gamma']
[[0.5 0.0 0.5 20.0] [0.5 0.25 0.75 20.0] [0.5 0.5 0.5 20.0] [0.0 0.0 0.0 20.0] [0.5 0.0 0.5 1.0] [0.5 0.5 1.0 20.0] [0.375 0.375 0.75 20.0] [0.125 0.125 0.25 20.0] [0.0 0.0 0.0 1.0]] _2pi / crystal



## Kpoints and energies

In [1]:
print('Quantum Espresso example:')
E=grep.kpointsEnergies('data/qe/results_bands/Si.bands.pwo')
print(f"Energies, ({E.eigenvalues.units}):")
print(E.eigenvalues[:3,:4],)
print(f"Kpoints, ({E.kpoints.units}):")
print(E.kpoints[:5])
print('Weights:')
print(E.weights[:5])

Quantum Espresso example:
Energies, (electron_volt):
[[-1.5082 -1.5082 -1.5082 -1.5082] [-1.5071 -1.5071 -1.5071 -1.5071] [-1.5038 -1.5038 -1.5038 -1.5038]] electron_volt
Kpoints, (_2pi / crystal):
[[0.5000000133031198 0.0 0.5000000133031198] [0.5000000133031198 0.01250002154578143 0.5125000348489013] [0.5000000133031198 0.02499997238088474 0.5249999856840045] [0.5000000133031198 0.03749999392666617 0.537500007229786] [0.5000000133031198 0.050000015472447604 0.5500000287755674]] _2pi / crystal
Weights:
[0.0070423 0.0070423 0.0070423 0.0070423 0.0070423]


In [3]:
E.kpoints=E.kpoints.magnitude*ureg('_2pi/alat')

In [6]:
lat=grep.lattice('data/qe/results_bands/Si.bands.pwo')
lat=lat/np.linalg.norm(lat[0])*ureg.alat
Klat=ut.reciprocal_basis(lat)
ut.cartesian2cryst(E.kpoints,Klat)

<Quantity([[0.50000001 0.         0.50000001]
 [0.50000001 0.01250002 0.51250003]
 [0.50000001 0.02499997 0.52499999]
 [0.50000001 0.03749999 0.53750001]
 [0.50000001 0.05000002 0.55000003]
 [0.50000001 0.06249997 0.56249998]
 [0.50000001 0.07499999 0.575     ]
 [0.50000001 0.08750001 0.58750002]
 [0.50000001 0.10000003 0.60000004]
 [0.50000001 0.11249998 0.6125    ]
 [0.50000001 0.125      0.62500002]
 [0.50000001 0.13750002 0.63750004]
 [0.50000001 0.14999998 0.64999999]
 [0.50000001 0.1625     0.66250001]
 [0.50000001 0.17500002 0.67500003]
 [0.50000001 0.18749997 0.68749998]
 [0.50000001 0.19999999 0.7       ]
 [0.50000001 0.21250001 0.71250003]
 [0.50000001 0.22500003 0.72500005]
 [0.50000001 0.23749999 0.7375    ]
 [0.50000001 0.25000001 0.75000002]
 [0.50000001 0.26250003 0.7375    ]
 [0.49999994 0.27499998 0.72499998]
 [0.50000001 0.2875     0.71250003]
 [0.50000001 0.30000002 0.7       ]
 [0.49999994 0.31249997 0.68749998]
 [0.50000001 0.32499999 0.67500003]
 [0.50000001 0.33750002 0.66250001]
 [0.50000001 0.35000004 0.64999999]
 [0.50000001 0.36249999 0.63750004]
 [0.50000001 0.37500001 0.62500002]
 [0.50000001 0.38750003 0.6125    ]
 [0.49999994 0.39999998 0.59999997]
 [0.50000001 0.4125     0.58750002]
 [0.50000001 0.42500003 0.575     ]
 [0.49999994 0.43749998 0.56249998]
 [0.50000001 0.45       0.55000003]
 [0.50000001 0.46250002 0.53750001]
 [0.50000001 0.47500004 0.52499999]
 [0.50000001 0.48749999 0.51250003]
 [0.50000001 0.50000001 0.50000001]
 [0.47499997 0.47499997 0.47499997]
 [0.45000007 0.45000007 0.45000007]
 [0.42500003 0.42500003 0.42500003]
 [0.39999998 0.39999998 0.39999998]
 [0.37499994 0.37499994 0.37499994]
 [0.35000004 0.35000004 0.35000004]
 [0.32499999 0.32499999 0.32499999]
 [0.29999995 0.29999995 0.29999995]
 [0.27500005 0.27500005 0.27500005]
 [0.25000001 0.25000001 0.25000001]
 [0.22499996 0.22499996 0.22499996]
 [0.20000006 0.20000006 0.20000006]
 [0.17500002 0.17500002 0.17500002]
 [0.14999998 0.14999998 0.14999998]
 [0.12499993 0.12499993 0.12499993]
 [0.10000003 0.10000003 0.10000003]
 [0.07499999 0.07499999 0.07499999]
 [0.04999994 0.04999994 0.04999994]
 [0.02500004 0.02500004 0.02500004]
 [0.         0.         0.        ]
 [0.02499997 0.         0.02499997]
 [0.05000002 0.         0.05000002]
 [0.07499999 0.         0.07499999]
 [0.10000003 0.         0.10000003]
 [0.125      0.         0.125     ]
 [0.14999998 0.         0.14999998]
 [0.17500002 0.         0.17500002]
 [0.19999999 0.         0.19999999]
 [0.22500003 0.         0.22500003]
 [0.25000001 0.         0.25000001]
 [0.27499998 0.         0.27499998]
 [0.30000002 0.         0.30000002]
 [0.32499999 0.         0.32499999]
 [0.34999997 0.         0.34999997]
 [0.37500001 0.         0.37500001]
 [0.39999998 0.         0.39999998]
 [0.42500003 0.         0.42500003]
 [0.45       0.         0.45      ]
 [0.47499997 0.         0.47499997]
 [0.50000001 0.         0.50000001]
 [0.50000001 0.50000001 1.00000003]
 [0.49374997 0.49374997 0.98749993]
 [0.48749999 0.48749999 0.97499998]
 [0.48125002 0.48125002 0.96250003]
 [0.47499997 0.47499997 0.94999994]
 [0.46874999 0.46874999 0.93749999]
 [0.46250002 0.46250002 0.92500004]
 [0.45624997 0.45624997 0.91249995]
 [0.45       0.45       0.9       ]
 [0.44375002 0.44375002 0.88750004]
 [0.43749998 0.43749998 0.87499995]
 [0.43125    0.43125    0.8625    ]
 [0.42500003 0.42500003 0.85000005]
 [0.41874998 0.41874998 0.83749996]
 [0.4125     0.4125     0.82500001]
 [0.40625003 0.40625003 0.81250006]
 [0.39999998 0.39999998 0.79999996]
 [0.39375001 0.39375001 0.78750001]
 [0.38750003 0.38750003 0.77500006]
 [0.38124999 0.38124999 0.76249997]
 [0.37500001 0.37500001 0.75000002]
 [0.36249999 0.36249999 0.72499998]
 [0.34999997 0.34999997 0.69999993]
 [0.33750002 0.33750002 0.67500003]
 [0.32499999 0.32499999 0.64999999]
 [0.31249997 0.31249997 0.62499995]
 [0.30000002 0.30000002 0.60000004]
 [0.2875     0.2875     0.575     ]
 [0.27499998 0.27499998 0.54999996]
 [0.26250003 0.26250003 0.5250

In [2]:
print('VASP EIGENVAL example:')
E=grep.kpointsEnergies('data/vasp/RESULTS/EIGENVAL')
print(f"Energies, ({E.eigenvalues.units}):")
print(E.eigenvalues[:3,:4],)
print(f"Kpoints, ({E.kpoints.units}):")
print(E.kpoints[:5])
print('Weights:')
print(E.weights[:5])

VASP EIGENVAL example:
Energies, (electron_volt):
[[-1.86626 -1.866259 3.089611 3.089627] [-1.865252 -1.865251 3.08052 3.080536] [-1.862249 -1.862248 3.053846 3.053862]] electron_volt
Kpoints, (_2pi / crystal):
[[0.5 0.0 0.5] [0.5 0.01315789 0.5131579] [0.5 0.02631579 0.5263158] [0.5 0.03947368 0.5394737] [0.5 0.05263158 0.5526316]] _2pi / crystal
Weights:
[0.00714286 0.00714286 0.00714286 0.00714286 0.00714286]


In [3]:
print('VASP OUTCAR example:')
E=grep.kpointsEnergies('data/vasp/RESULTS/OUTCAR')
print(f"Energies, ({E.eigenvalues.units}):")
print(E.eigenvalues[:3,:4],)
print(f"Kpoints, ({E.kpoints.units}):")
print(E.kpoints[:5])
print('Weights:')
print(E.weights[:5])

VASP OUTCAR example:
Energies, (electron_volt):
[[-1.8663 -1.8663 3.0896 3.0896] [-1.8653 -1.8653 3.0805 3.0805] [-1.8622 -1.8622 3.0538 3.0539]] electron_volt
Kpoints, (_2pi / crystal):
[[0.5 0.0 0.5] [0.5 0.013158 0.513158] [0.5 0.026316 0.526316] [0.5 0.039474 0.539474] [0.5 0.052632 0.552632]] _2pi / crystal
Weights:
[0.007143 0.007143 0.007143 0.007143 0.007143]


## Kpoints and frequencies

In [12]:
print('Quantum Espresso example:')
F=grep.kpointsFrequencies('data/qe/results_matdyn/Si.freq')
print(f"Frequencies ({F.eigenvalues.units}):")
print(F.eigenvalues[:2])
print(f"Kpoints ({F.kpoints.units}):")
print(F.kpoints[:5])

Quantum Espresso example:
Frequencies (speed_of_light / centimeter):
[[689.1662 689.1662 897.3373 897.3373 946.9531 946.9531] [689.4236 689.4236 897.1973 897.1973 947.1141 947.1141]] speed_of_light / centimeter
Kpoints (_2pi / alat):
[[0.0 0.707107 0.0] [0.017678 0.707107 0.0] [0.035355 0.707107 0.0] [0.053033 0.707107 0.0] [0.070711 0.707107 0.0]] _2pi / alat


--- 
Edited until here more or less...

## BandGAP

In [5]:
direct,indirect=qe_out.grep_gap()
print('For QE:')
print('Direct gap= ',direct,'eV , Indirect gap=', indirect, ' meV')

NameError: name 'qe_out' is not defined

## Kpoints, energies and projections

Scrapping of either:
- Quantum Espresso **proj.pwo** output 
- VASP PROCAR file

for further postprocessing.

In [ ]:
returns STATES, KPOINTS, ENERGIES, PROJECTIONS=qe_out.grep_kpoints_energies_projections()

## Phonon grid

In [9]:
#Read the phonon grid and structure from a ph.x output
ph_out=utils.file('DATA/phonons/3x3x2/results_ph/CsV3Sb5.ph.pwo')
ph_out.grep_ph_grid_points()
print('The phonon grid used in the calculation is:')
print(ph_out.ph_grid_points)

The phonon grid used in the calculation is:
[[ 0.     0.     0.   ]
 [ 0.     0.    -0.5  ]
 [ 0.     0.333  0.   ]
 [-0.333  0.333  0.   ]
 [ 0.333 -0.     0.   ]
 [-0.333  0.     0.   ]
 [ 0.333 -0.333  0.   ]
 [ 0.    -0.333  0.   ]
 [ 0.     0.333 -0.5  ]
 [-0.333  0.333 -0.5  ]
 [ 0.333 -0.    -0.5  ]
 [-0.333  0.    -0.5  ]
 [ 0.333 -0.333 -0.5  ]
 [ 0.    -0.333  0.5  ]
 [ 0.333  0.333  0.   ]
 [-0.333 -0.333  0.   ]
 [ 0.333  0.333 -0.5  ]
 [-0.333 -0.333  0.5  ]]


# II. Transforming tools

In [30]:
qe_out=utils.file('DATA/bands/QE/results_scf/CsV3Sb5.scf.pwo')
rec_basis=qe_out.reciprocal_lattice()
print('Reciprocal basis:')
print(rec_basis)
print()
M_cryst=[1/2,0,0]
M_cart=utils.cryst2cartesian(M_cryst,rec_basis)
print('The M point in crystal units is:', M_cryst)
print('The M point in cartesian units is:', M_cart)

Reciprocal basis:
[[0.18169622 0.10490241 0.        ]
 [0.         0.20980483 0.        ]
 [0.         0.         0.10123757]]

The M point in crystal units is: [0.5, 0, 0]
The M point in cartesian units is: [0.09084811 0.05245121 0.        ]
